export const FIND_PERSONS='FIND_PERSONS'
export const GET_ORDERS_COUNT='GET_ORDERS_COUNT'
export const GET_PERSONS_COUNT='GET_PERSONS_COUNT'
export const GET_ORDERS='GET_ORDERS'
export const GET_PERSON='GET_PERSON'
export const GET_ORDER='GET_ORDER'
export const DELETE_ITEM='DELETE_ITEM'
export const ADD_PERSON='ADD_PERSON'
export const ADD_ORDER='ADD_ORDER'
export const SET_PERSONS="SET_PERSONS"
export const SET_ORDERS='SET_ORDERS'

export const SET_PAGINAT="SET_PAGINAT"